"""
Prometheus Metrics for Creative Engine (Task 10.7).

Tracks workflow execution health, performance, and output quality.
"""

import time
from typing import Optional
from contextlib import contextmanager
from prometheus_client import Counter, Gauge, Histogram, CollectorRegistry


# ============================================================================
# Custom Registry (separate from Layer 4 monitoring metrics)
# ============================================================================

CREATIVE_ENGINE_REGISTRY = CollectorRegistry()


# ============================================================================
# Workflow Execution Metrics
# ============================================================================

# Counter: Total workflow runs
creative_engine_runs_total = Counter(
    name="creative_engine_runs_total",
    documentation="Total number of Creative Engine workflow runs",
    labelnames=["status"],  # success, error
    registry=CREATIVE_ENGINE_REGISTRY,
)

# Histogram: Duration per workflow step
creative_engine_step_duration_seconds = Histogram(
    name="creative_engine_step_duration_seconds",
    documentation="Duration of each workflow step in seconds",
    labelnames=["step"],  # generate, validate, compile, simulate, score, persist
    registry=CREATIVE_ENGINE_REGISTRY,
    buckets=(0.5, 1, 2, 5, 10, 20, 30, 60, 120),  # 0.5s to 2min
)

# Histogram: Total workflow duration
creative_engine_workflow_duration_seconds = Histogram(
    name="creative_engine_workflow_duration_seconds",
    documentation="Total workflow execution duration in seconds",
    labelnames=["status"],
    registry=CREATIVE_ENGINE_REGISTRY,
    buckets=(5, 10, 20, 30, 60, 120, 180, 300),  # 5s to 5min
)


# ============================================================================
# Output Metrics
# ============================================================================

# Counter: Candidates generated by bucket
creative_engine_candidates_generated = Counter(
    name="creative_engine_candidates_generated",
    documentation="Total strategy candidates generated",
    labelnames=["bucket"],  # low, medium, high
    registry=CREATIVE_ENGINE_REGISTRY,
)

# Gauge: Score distribution (summary stats)
creative_engine_score_latest = Gauge(
    name="creative_engine_score_latest",
    documentation="Latest strategy score generated",
    registry=CREATIVE_ENGINE_REGISTRY,
)


# ============================================================================
# Failure Metrics
# ============================================================================

# Counter: Failures by step and reason
creative_engine_failures_total = Counter(
    name="creative_engine_failures_total",
    documentation="Total failures in workflow execution",
    labelnames=["step", "reason"],  # step: validate/compile/simulate, reason: timeout/schema/etc
    registry=CREATIVE_ENGINE_REGISTRY,
)


# ============================================================================
# Timing Metrics
# ============================================================================

# Gauge: Last successful run timestamp
creative_engine_last_run_timestamp = Gauge(
    name="creative_engine_last_run_timestamp",
    documentation="Unix timestamp of last successful workflow run",
    registry=CREATIVE_ENGINE_REGISTRY,
)

# Gauge: Time since last successful run
creative_engine_time_since_last_run_seconds = Gauge(
    name="creative_engine_time_since_last_run_seconds",
    documentation="Seconds since last successful workflow run",
    registry=CREATIVE_ENGINE_REGISTRY,
)


# ============================================================================
# Tracking Functions
# ============================================================================

def track_workflow_run(status: str, duration: float):
    """
    Track a complete workflow run.

    Args:
        status: "success" or "error"
        duration: Execution time in seconds
    """
    creative_engine_runs_total.labels(status=status).inc()
    creative_engine_workflow_duration_seconds.labels(status=status).observe(duration)

    if status == "success":
        creative_engine_last_run_timestamp.set(time.time())


def track_step_duration(step: str, duration: float):
    """
    Track individual step execution time.

    Args:
        step: Step name (generate, validate, compile, simulate, score, persist)
        duration: Execution time in seconds
    """
    creative_engine_step_duration_seconds.labels(step=step).observe(duration)


def track_candidate_generated(bucket: str, score: float):
    """
    Track a generated candidate.

    Args:
        bucket: Risk bucket (low, medium, high)
        score: Strategy score
    """
    creative_engine_candidates_generated.labels(bucket=bucket.lower()).inc()
    creative_engine_score_latest.set(score)


def track_failure(step: str, reason: str):
    """
    Track a workflow failure.

    Args:
        step: Step where failure occurred
        reason: Failure reason (timeout, schema_error, http_error, etc.)
    """
    creative_engine_failures_total.labels(step=step, reason=reason).inc()


def update_time_since_last_run():
    """
    Update the time-since-last-run metric.

    Should be called periodically (e.g., by scheduler) to keep metric fresh.
    """
    last_run = creative_engine_last_run_timestamp._value.get()
    if last_run > 0:
        time_since = time.time() - last_run
        creative_engine_time_since_last_run_seconds.set(time_since)


@contextmanager
def track_step_execution(step: str):
    """
    Context manager for automatic step timing.

    Args:
        step: Step name

    Example:
        >>> with track_step_execution("validate"):
        >>>     result = validate(spec)
    """
    start_time = time.time()
    try:
        yield
    finally:
        duration = time.time() - start_time
        track_step_duration(step, duration)


@contextmanager
def track_workflow_execution():
    """
    Context manager for automatic workflow timing and status tracking.

    Example:
        >>> with track_workflow_execution():
        >>>     result = run_creative_engine_sync()
    """
    start_time = time.time()
    status = "error"  # Default to error

    try:
        yield
        status = "success"
    except Exception:
        status = "error"
        raise
    finally:
        duration = time.time() - start_time
        track_workflow_run(status, duration)


# ============================================================================
# Metrics Export
# ============================================================================

def get_creative_engine_metrics() -> bytes:
    """
    Get Prometheus-formatted metrics for Creative Engine.

    Returns:
        Metrics in Prometheus text format

    Example:
        >>> from fastapi import Response
        >>> from core.workflows.metrics import get_creative_engine_metrics
        >>>
        >>> @app.get("/metrics/creative-engine")
        >>> def creative_engine_metrics():
        >>>     return Response(
        >>>         get_creative_engine_metrics(),
        >>>         media_type="text/plain"
        >>>     )
    """
    from prometheus_client import generate_latest
    return generate_latest(CREATIVE_ENGINE_REGISTRY)


# ============================================================================
# Metrics Summary (Debugging)
# ============================================================================

def print_creative_engine_metrics_summary():
    """
    Print a human-readable summary of Creative Engine metrics.

    Useful for debugging and manual inspection.
    """
    print("=" * 70)
    print("Creative Engine Metrics Summary")
    print("=" * 70)

    # Workflow runs
    success_count = creative_engine_runs_total.labels(status="success")._value.get()
    error_count = creative_engine_runs_total.labels(status="error")._value.get()
    print(f"Workflow Runs: {success_count + error_count} total")
    print(f"  Success: {success_count}")
    print(f"  Error: {error_count}")

    # Candidates by bucket
    low = creative_engine_candidates_generated.labels(bucket="low")._value.get()
    medium = creative_engine_candidates_generated.labels(bucket="medium")._value.get()
    high = creative_engine_candidates_generated.labels(bucket="high")._value.get()
    print(f"\nCandidates Generated: {low + medium + high} total")
    print(f"  Low Risk: {low}")
    print(f"  Medium Risk: {medium}")
    print(f"  High Risk: {high}")

    # Latest score
    latest_score = creative_engine_score_latest._value.get()
    print(f"\nLatest Strategy Score: {latest_score:.2f}")

    # Last run
    last_run_ts = creative_engine_last_run_timestamp._value.get()
    if last_run_ts > 0:
        from datetime import datetime
        last_run_dt = datetime.fromtimestamp(last_run_ts)
        print(f"\nLast Successful Run: {last_run_dt.strftime('%Y-%m-%d %H:%M:%S')}")

        time_since = time.time() - last_run_ts
        minutes_since = int(time_since / 60)
        print(f"Time Since Last Run: {minutes_since} minutes")
    else:
        print("\nNo successful runs yet")

    print("=" * 70)
    print("\nFor full metrics, expose /metrics/creative-engine endpoint")
